### PR TITLE
JBIDE-21171: Removing bower / npm / node plugins after migration to eclipse jsdt project

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
+1

**Comment by nickboldt** [comment]
Don't we actually want to replace this feature w/ the org.eclipse.wst.jsdt.nodejs.feature_1.0.0.v201512020037 one, rather than simply removing it?

**Comment by alexeykazakov** [comment]
Yes we do, but it's OK to remove it first and then add the jsdt one in a separate PR.

**Comment by nickboldt** [comment]
Replaced by https://github.com/jbosstools/jbosstools-build-sites/commit/c9e5c8a74e44bd690291ba9bce04f91ea4ed0267

**Pull request closed without merging**
