### PR TITLE
FUSETOOLS-2922 - adding wsdl2rest tests

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
Looks good but can't merge until these plugins appear on the latest snapshot site:

http://download.jboss.org/jbosstools/oxygen/snapshots/builds/jbosstools-fuse_master/latest/all/repo/plugins/

**Comment by bfitzpat** [comment]
Looks like everything BUT the wsdl2rest tests are in that build. Will investigate. Thanks.

**Comment by nickboldt** [comment]
Yes, it appears you didn't add them to the site/category.xml file.

view-source:https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Fuse%20Tooling/job/jbosstools-fuse_master/613/artifact/sources/site/target/repository/category.xml

**Comment by bfitzpat** [comment]
Created PR https://github.com/jbosstools/jbosstools-fuse/pull/1373 to handle that change

**Comment by bfitzpat** [comment]
The missing plug-ins now appear in http://download.jboss.org/jbosstools/oxygen/snapshots/builds/jbosstools-fuse_master/latest/all/repo/plugins/

**Comment by bfitzpat** [comment]
@nickboldt please let me know if you need anything else here. thanks for your help!

**Pull request merged**
