### PR TITLE
JBIDE-21821 JBIDE-21233 since we now always...

### PR DESCRIPTION
**Pull request by nickboldt**
JBIDE-21821 JBIDE-21233 since we now always co-publish the JBT site w/ its TP, we no longer need this assoc site anymore

### CODE REVIEW

**Comment by mickaelistria** [comment]
+1

**Comment by nickboldt** [comment]
@mickaelistria thanks, can you review again? Added more cleanups (some related, some tangential).

**Comment by mickaelistria** [comment]
All look good, I just have 1 question: by co-publish, you mean that the JBT site now includes its dependencies directly, or that there are composited? If the later, how are those composites generated (I remember that associateSites has multiple "flavours")

**Comment by nickboldt** [comment]
Co-publish as in:

http://download.jboss.org/jbosstools/mars/development/updates/compositeContent.xml
or
http://download.jboss.org/jbosstools/mars/snapshots/updates/compositeContent.xml

generated via http://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_9.0.mars/job/jbosstools-discovery_4.3.mars/ -> http://download.jboss.org/jbosstools/mars/snapshots/updates/discovery.central/4.3.mars/

then we symlink:
/mars/snapshots/updates/compositeContent.xml -> discovery.central/4.3.mars/compositeContent.xml
/mars/snapshots/updates/compositeArtifacts.xml -> discovery.central/4.3.mars/compositeArtifacts.xml

And voila!

**Comment by mickaelistria** [comment]
Wasn't it the associateSites that generates those composite?

**Comment by nickboldt** [comment]
No, associateSites in the pom generated references in content.xml:

   <references size="2">
      <repository options="1" type="0"
                  uri="http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/mars/"
                  url="http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/mars/"/>
      <repository options="1" type="1"
                  uri="http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/mars/"
                  url="http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/mars/"/>
   </references>

**Comment by mickaelistria** [comment]
It can do composites, see JBIDE-18541

**Comment by nickboldt** [comment]
Sure, but in our scenario that would be a circular dependency since we build the JBT aggregate THEN the JBT central site ... and THEN we composite them together.

JBTIS doesn't have the notion of a separate Central site (containing 3rd party content, or containing EA content that's in JBT but not JBDS), so they build things differently.

Our discovery job does the orchestration of the composite sites used for JBT+Central+2xTPs, JBT+Central+EA+3xTPs, JBDS+Central+2xTPs, JBDS+Central+EA+3xTPs.

**Pull request merged**
