### PR TITLE
JBDS-3263 Remove JSF Visual/Source and Preview Tabs

### PR DESCRIPTION
**Pull request by kmarmaliykov**

### CODE REVIEW

**Comment by nickboldt** [comment]
Most of these changes are not needed since org.jboss.tools.vpe.test.feature contains org.jboss.tools.vpe.preview.test.feature and org.jboss.tools.vpe.feature contains org.jboss.tools.vpe.feature. Not sure if we can remove all the xulrunner stuff entirely.

@kmarmaliykov  are you sure it's no longer needed for ANY OSes?

**Comment by maxandersen** [comment]
JBDS-3263 was already closed and verified. 

Is this not just a stale/outofdate PR or do you have a suspicion that JBDS-3263 was closed wrongly ? then should reopen that jira or create new one this PR could be adjusted/rebased for.

**Comment by nickboldt** [comment]
Not stale/outofdate, just forgotten to apply. That's why I asked @kmarmaliykov for comments about why he'd asked to remove xulrunner from update sites. If in fact this PR is NOT NEEDED then I would ask that he simply close it. Same goes for https://github.com/jbosstools/jbosstools-build/pull/180 which I believe was also forgotten to apply.

**Comment by maxandersen** [comment]
then lets reopen the jira if any doubt about it.

**Comment by nickboldt** [comment]
I was going to do that IF/WHEN @kmarmaliykov  replied, but sure, why not generate some JIRA spam first? *grumble grumble*

**Comment by maxandersen** [comment]
because jira actually shows up in overviews and queries for what is outstanding.

opening the jira would generate *less* spam than the cross-comments on github and jira thats been here now ;)

**Comment by nickboldt** [comment]
" PR #182 was needed only if we will remove vpe plugins and xulrunner. Since we will not do it, this PR(as far as other PRs which removes vpe) should be rejected." - Konstantin in https://issues.jboss.org/browse/JBDS-3263

**Pull request closed without merging**
