### PR TITLE
JBIDE-20261 Include jst.js.feature into aggregated p2 repository

### PR DESCRIPTION
**Pull request by dgolovin**
Fix includes jst.js.feature into JBossTools aggregated p2 repository
into web and mobile categories.

### CODE REVIEW

**Comment by nickboldt** [comment]
Where is the feature? I don't see it in https://github.com/jbosstools/jbosstools-jst/tree/master/features :(

**Comment by dgolovin** [comment]
Should be pushed after https://github.com/jbosstools/jbosstools-jst/pull/501

**Comment by nickboldt** [comment]
OK, +1 after PR 501 is applied & built. 

Should this also be added to JBDS update site? Central? JBDS BYOE feature?

**Comment by dgolovin** [comment]
PR 501 released to master, build is done and p2repo is published

**Comment by dgolovin** [comment]
rebased and released to master.

**Comment by nickboldt** [comment]
So this is JUST for JBoss Tools? 

Should this also be added to JBDS update site? Central? JBDS BYOE feature?

**Comment by nickboldt** [comment]
pushed to Beta2x branch: https://github.com/jbosstools/jbosstools-build-sites/commit/b8a888810bf9217e5795f7722953efca58f0e84e

**Pull request closed without merging**
